# Form implementation generated from reading ui file 'assistant/gui/base.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(502, 398)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(35, 39, 49);\n"
"    border-radius: 10px;\n"
"}")
        self.main_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_frame.sizePolicy().hasHeightForWidth())
        self.title_frame.setSizePolicy(sizePolicy)
        self.title_frame.setMinimumSize(QtCore.QSize(0, 25))
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 25))
        self.title_frame.setToolTipDuration(-1)
        self.title_frame.setStyleSheet("QFrame {\n"
"}")
        self.title_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.min_button = QtWidgets.QPushButton(self.title_frame)
        self.min_button.setMinimumSize(QtCore.QSize(14, 14))
        self.min_button.setMaximumSize(QtCore.QSize(14, 14))
        self.min_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(67, 203, 68);\n"
"    border-radius: 7px;\n"
"}")
        self.min_button.setText("")
        self.min_button.setObjectName("min_button")
        self.horizontalLayout.addWidget(self.min_button)
        self.max_button = QtWidgets.QPushButton(self.title_frame)
        self.max_button.setMinimumSize(QtCore.QSize(14, 14))
        self.max_button.setMaximumSize(QtCore.QSize(14, 14))
        self.max_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(248, 188, 58);\n"
"    border-radius: 7px;\n"
"}")
        self.max_button.setText("")
        self.max_button.setObjectName("max_button")
        self.horizontalLayout.addWidget(self.max_button)
        self.exit_button = QtWidgets.QPushButton(self.title_frame)
        self.exit_button.setMinimumSize(QtCore.QSize(14, 14))
        self.exit_button.setMaximumSize(QtCore.QSize(14, 14))
        self.exit_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(243, 91, 90);\n"
"    border-radius: 7px;\n"
"}")
        self.exit_button.setText("")
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout.addWidget(self.exit_button)
        self.verticalLayout_2.addWidget(self.title_frame)
        self.content_frame = QtWidgets.QFrame(self.main_frame)
        self.content_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content_frame.setObjectName("content_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.content_frame)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_frame = QtWidgets.QFrame(self.content_frame)
        self.widget_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.widget_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.widget_frame.setObjectName("widget_frame")
        self.verticalLayout_3.addWidget(self.widget_frame)
        self.input_frame = QtWidgets.QFrame(self.content_frame)
        self.input_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.input_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.input_frame.setObjectName("input_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.input_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.input_box = QtWidgets.QLineEdit(self.input_frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.input_box.setFont(font)
        self.input_box.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(35, 39, 49);\n"
"    color: rgb(236, 236, 236);\n"
"    border: 1px solid rgb(236, 236, 236);\n"
"    border-radius: 7px;\n"
"}")
        self.input_box.setObjectName("input_box")
        self.horizontalLayout_2.addWidget(self.input_box)
        self.enter_button = QtWidgets.QPushButton(self.input_frame)
        self.enter_button.setMinimumSize(QtCore.QSize(40, 30))
        self.enter_button.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.enter_button.setFont(font)
        self.enter_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(242, 80, 34);\n"
"    color: rgb(235, 235, 235);\n"
"    border-radius: 10px;\n"
"}")
        self.enter_button.setObjectName("enter_button")
        self.horizontalLayout_2.addWidget(self.enter_button)
        self.verticalLayout_3.addWidget(self.input_frame)
        self.verticalLayout_2.addWidget(self.content_frame)
        self.verticalLayout.addWidget(self.main_frame)
        main_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.enter_button.setText(_translate("main_window", ">"))
